name: Deploy GitHub Pages (Forked mdBook)

on:
	push:
		branches:
			- main

jobs:
	deploy:
		runs-on: ubuntu-18.04
		steps:
			- uses: actions/checkout@v2

			- name: Setup mdBook
				uses: chenbobby/actions-mdbook@v1
		
			- run: mdbook build

			- name: Deploy static website
				uses: peaceiris/actions-gh-pages@v3
				with:
					github_token: ${{ secrets.GITHUB_TOKEN }}
					publish_dir: ./book
